apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-security-service-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mobile-security-service-operator
  template:
    metadata:
      labels:
        name: mobile-security-service-operator
    spec:
      serviceAccountName: mobile-security-service-operator
      containers:
        - name: mobile-security-service-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - mobile-security-service-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mobile-security-service-operator"
